### ISSUE TITLE
elmstatic watch exiting on code 1 in docker

### ISSUE THREAD

**Issue by peterchappy** [alexkorban/elmstatic#10]
I'm trying to run `elmstatic watch` inside of a docker container and it keeps exiting before it compiles the layout. Examples below.
```
uicontainer | Building the site
uicontainer |   Compiling layouts
uicontainer exited with code 1
```

Example of Dockerfile

```
FROM node:10

RUN mkdir /app
WORKDIR /app

ADD docker-entrypoint.sh docker-entrypoint.sh
RUN yarn add -g elm elmstatic browser-sync

ENV NODE_PATH=/app/node_modules:/app/src
ENV PATH=$PATH:/app/node_modules/.bin

EXPOSE 3000

ENTRYPOINT ["/bin/bash", "/app/docker-entrypoint.sh"]
CMD ["watch"]
```

watch command

```
elmstatic watch
```

I can get `elmstatic watch` to run locally fine. Any ideas would be greatly appreciated. I'd love to use this framework for my portfolio site.

**Comment by alexkorban** [comment]
It looks like it’s failing to compile the layouts (perhaps it can’t find the Elm executable?). Have you tried running `elmstatic -v` to get more output?

**Comment by peterchappy** [comment]
Thanks for the 🦆
