### ISSUE TITLE
Version in package-lock.json is incorrect

### ISSUE THREAD

**Issue by dnk8n** [alexkorban/elmstatic#11]
Should the package-lock.json at https://github.com/alexkorban/elmstatic/blob/v0.6.1/package-lock.json not show:

```
{
  "name": "elmstatic",
  "version": "0.6.1",
  ...
}
```

It currently shows:

```
{
  "name": "elmstatic",
  "version": "0.4.1",
  ...
}
```

**Comment by alexkorban** [comment]
Yes! Didn't realise I have to maintain that manually. Additionally, instead of package-lock.json I should have npm-shrinkwrap.json. I made the change in Elmstatic 0.6.2.

**Comment by dnk8n** [comment]
Great work.

I did notice later on that an npn install actually modified the
package-lock.json so it's effects will actually be negligible.
