### ISSUE TITLE
elmstatic build issue with elm 0.19.1

### ISSUE THREAD

**Issue by wsconlon** [alexkorban/elmstatic#16]
'main' has to be exported unnecessarily from ElmMarkup and Style to get _site to build.  Is there a cleaner way to deal with this?  Thanks!

**Comment by alexkorban** [comment]
Not at the moment. I need to change Elmstatic to only compile files with `main` to properly support Elm 0.19.1.

**Comment by alexkorban** [comment]
Elm 0.19.1 is supported in v0.6.3.

**Comment by wsconlon** [comment]
Thanks!  I would have fixed it if I knew how.
