### ISSUE TITLE
Running `elmstatic build` without elm fails without error

### ISSUE THREAD

**Issue by dcellucci** [alexkorban/elmstatic#18]
Hello!

I know this is kind of niche, but if you follow the instructions here https://korban.net/elm/elmstatic/ with a fresh node environment, `elmstatic build` and `elmstatic listen` will fail on the `elm make` step but won't print an error.

**Comment by alexkorban** [comment]
Good catch! An error message is particularly useful when the path to the Elm compiler is specified in config.json. 

Fixed in 0.6.4 - Elmstatic will output an error message.
