### ISSUE TITLE
Elmstatic fails with "could not find Elm compiler"

### ISSUE THREAD

**Issue by JonathanReeve** [alexkorban/elmstatic#2]
Hi! Thanks for this awesome program. It's really elegant-looking, and I can't wait to play around with it. Unfortunately, I haven't been able to get it to work, yet. This might be because my distro (NixOS) has Elm 0.19. I have a feeling maybe these errors would all go away if everyone bumped to 0.19, if it's not too much of an operation. Here are the errors I encounter, and the commands that generate them:

```
⟩ nix-env -iA nixos.nodejs
installing 'nodejs-8.11.4'
building '/nix/store/r832d7xx9m036s6qs40jj383is6zz80j-user-environment.drv'...
created 3331 symlinks in user environment

⟩ npm install -g elmstatic
/home/jon/.npm-global/bin/elmstatic -> /home/jon/.npm-global/lib/node_modules/elmstatic/bin/index.js
+ elmstatic@0.3.4
updated 1 package in 2.731s

⟩ elmstatic
Cleaning out the output path (output)...
Generating global styles...
Could not find Elm compiler "elm-make". Is it installed?

⟩ elm make
-- NO INPUT --------------------------------------------------------------------

What should I make though? I need more information, like:

    elm make src/Main.elm
    elm make src/This.elm src/That.elm

However many files you give, I will create one JS file out of them.

```

**Comment by alexkorban** [comment]
You're right, Elm 0.19 isn't going to work. Unfortunately, I can't upgrade Elmstatic to Elm 0.19 until elm-static-html-lib is upgraded, and so far it hasn't been. Is it possible to install Elm 0.18 on NixOS (eg locally for the project with `npm install elm@0.18.0`)?

**Comment by JonathanReeve** [comment]
Is it just a matter of incrementing the version of elm-node-compiler in elm-static-html-lib's package.json? I'm not a node guy, so I'm having a hard time getting elmstatic to work with my customized version of elm-static-html-lib (and I'm on NixOS, so that makes it a lot harder).

**Comment by alexkorban** [comment]
Unfortunately not. elm-static-html-lib relies on "native code" which is no longer permitted in Elm 0.19, so it has to be reworked with some kind of different approach. 

If you're able to install Elmstatic with `npm install`, I thought you'd be able to install Elm 0.18 with `npm install elm@0.18.0`. If that works, then you should be able to run `npx elmstatic`. Does that not work?

**Comment by JonathanReeve** [comment]
If I install elm 0.18, with `npm install -g elm@0.18.0`, then install elmstatic with `npm install -g elmstatic`, and try to run `elmstatic init` followed by `elmstatic`, I get this error:

```
⟩ elmstatic
Cleaning out the output path (output)...
Generating global styles...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/jon/.npm-global/lib/node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm-make ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
Encountered a problem:  1
```
Any ideas what this could be?

**Comment by alexkorban** [comment]
`ENOENT` suggests that it's unable to find `elm-make` at that path when trying to launch it as a child process.

**Comment by janwirth** [comment]
Same issue here.

**Comment by brabster** [comment]
I got this working - the problem for me was that there's no `package.json` in my site directory. Without it, npm can't install a "local" 0.18.0 version of elm, so you can't refer to it in your `config.json`.

I created a `package.json` file in the root of my project directory with `{}` in it, so that it was a valid JSON file. Then I could `npm install elm@0.18.0` - which created a `node_modules/.bin/elm-make`.

Once that's done, you can refer to as the `elm` property in your `config.json` as per instructions at https://korban.net/elm/elmstatic and the `elmstatic` command will work.

This will also help if you want to install `http-server` locally instead of globally.

**Comment by alexkorban** [comment]
Thanks for writing down these steps @brabster. I'm able to install elm@0.18.0 without a package.json but it must depend on the platform/version of Node so hopefully your instructions will help out other people.

**Comment by alexkorban** [comment]
Elmstatic now works with Elm 0.19
