### ISSUE TITLE
Support YAML in Markdown frontmatter 

### ISSUE THREAD

**Issue by kioba** [alexkorban/elmstatic#20]
Tags has to be specified for each post and it can not be left empty.

error message:

```
Expecting an OBJECT with a field named `tags`
Error! Watching for more changes...
```

Tags are not parsed in case of correct one liner yaml syntax (error)

```
tags: [kotlin, functional]
```
error message:

```
Undeclared tags: [[kotlin,, arrow,, functional]]
You can declare tags in config.json
Error! Watching for more changes...
````

Tags are not parsed in case of correct yaml syntax but no error is generated. An example for yaml syntax:

```
tags: 
  - kotlin
  - functional
```

version:
```
$ elmstatic --version
0.6.6
```

As I understand only titles allow to be quoted the rest of the strings in metadata are not.
Both `Jekyll` and `Hugo` supports yaml syntax for Front Matter between triple dash. Would you mind if the syntax would be standardized with `yaml`?

**Comment by kioba** [comment]
I am happy to contribute changes to introduce yaml Front Matter parsing in case you agree with it 🙂

**Comment by alexkorban** [comment]
Sure, thanks, as long as it's backward-compatible (still allowing a space-separated list of tags) and supports CRLF line endings.

**Comment by kioba** [comment]
I have to make some research about backward compatibility, I will get back to you later. Thanks! :)

**Comment by kioba** [comment]
I tested with a couple of solution and `yaml` can parse the original space separated list as a string. That is lucky for us becasue we dont have to deal with custom tags.

An example what happens with the current behaviour with yaml parse:

`tags: first second third` -> ` { "tags" : "first second third" }`

Currently how the compatibility works the following:
1) we parse the tags with yaml
2) if the tags is not present, an empty array will be provided
3) if the tags is present and type is string, the value will be split
4) the rest is standard yaml work

**Comment by alexkorban** [comment]
Support for YAML added in v0.6.7. Thanks for the PR!
