### ISSUE TITLE
`spawn ENOENT` on Windows

### ISSUE THREAD

**Issue by zdebeer99** [alexkorban/elmstatic#4]
I got an spawnsync error on windows, I replaced the 'child_process' in the file 'bin/elmstatic.js' file with 'cross-spawn' node library, this then worked.

```js
const {spawn} = require("cross-spawn")
...
    const res = spawn.sync(command, R.flatten(args), { stdio: 'inherit' })
```

also had to install "cross-spawn": "^6.0.5", in the dependencies.

**Comment by alexkorban** [comment]
Thank you for suggesting a fix! Fixed in 0.4.1.
