### ISSUE TITLE
Elmstatic watch process ends when there is an Elm syntax error

### ISSUE THREAD

**Issue by joecorkerton** [alexkorban/elmstatic#7]
While running `elmstatic watch`, if I save a file which has an Elm syntax error, the process will end and return null.

Expected behaviour: Process displays elm compiler error in terminal but continues to run without updating files

**Comment by alexkorban** [comment]
Indeed! I got over-enthusiastic with exception handling. Fixed in v0.5.1, except it still aborts during the initial full build. I'd like to think how best to deal with those errors.
