### ISSUE TITLE
Add support for .emu files

### ISSUE THREAD

**Issue by joecorkerton** [alexkorban/elmstatic#8]
I liked the article that you wrote about playing around with `elm-markup`, but wondering if you would consider adding support for `.emu` markup files? (to avoid the 'hack' of putting the markup inside a .md file)

**Comment by alexkorban** [comment]
I'm not sure what to do about the preamble in that case. If I keep it, it's really not much different from the solution in the post, and besides it seems like metadata should be expressed in `elm-markup`. But without the preamble, I'm not sure how the layout would be specified – and layout has to be known before any Elm code runs. Any ideas?

**Comment by joecorkerton** [comment]
`Mark.documentWith` (https://package.elm-lang.org/packages/mdgriffith/elm-markup/latest/Mark#documentWith) supports metadata, which could contain the same data that is currently in the preamble. Extracting that with js may be trickier than the current md preamble solution though.

Possibly trying to enforce some syntax might help (the same way there is loose enforcement right now that you have a preamble in the markdown file with a title field) e.g. the top level record must be called "Article" 

Here's an example of documentWith in use https://github.com/mdgriffith/elm-markup/tree/3.0.1/examples/blog

**Comment by alexkorban** [comment]
I'll consider it. I think elm-markup offers interesting possibilities but I'm wary of adding more complexity as I have limited time for Elmstatic.

**Comment by dillonkearns** [comment]
Hello @alexkorban and @joecorkerton!

I just wanted to give a heads up here that I'll be announcing an `elm-markup`-based site generator in the next week or two. It's in a usable state right now, but it's likely to change a lot in the coming weeks.

Here's an example site built with `elm-pages`: https://github.com/dillonkearns/elm-pages/tree/master/site. The framework builds as much as possible on the idea of type-safety. So you get an `elm-markup` error message if you do a relative link to a page which doesn't exist in the site. Or if you try to refer to an image asset which doesn't exist.

I'll keep you posted!

**Comment by alexkorban** [comment]
Incidentally, I've almost completed `elm-markup` support in Elmstatic. It only reports basic parsing errors for now, but in principle it could validate links and other things as well.

**Comment by alexkorban** [comment]
Supported as of v0.6.0. Migration from existing Markdown content would have to be done manually though!
